name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jdk:
    name: JDK Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [17, 21, 25-ea]
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: maven

      - name: JDK Tests ${{ matrix.jdk }}
        run: ./mvnw -B clean install artifact:compare -Dmaven.test.failure.ignore=true -Dansi.strip=true

      - name: Test Logs
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: ${{ matrix.jdk }}-test-results
          path: "**/target/*-reports*/**/TEST-*.xml"
  jdk-summary:
    name: JDK Build Summary
    runs-on: ubuntu-latest
    needs: jdk
    if: always()
    steps:
      - name: Check matrix job outcomes
        run: |
          if [[ "${{ needs.jdk.result }}" != "success" ]]; then
            echo "One or more matrix jobs failed."
            exit 1
          else
            echo "All matrix jobs succeeded."
          fi
