name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  jdk:
    name: JDK Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [17, 21, 25]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: maven

      - name: JDK Tests ${{ matrix.jdk }}
        run: ./mvnw -B clean install artifact:compare -Dmaven.test.failure.ignore=true -Dansi.strip=true ${{ matrix.jdk == 17 && '-Pcoverage' || '' }}

      - name: Generate aggregate coverage report
        if: matrix.jdk == 17
        run: ./mvnw -B verify -PjacocoReport -Dansi.strip=true

      - name: Test Logs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: success() || failure()
        with:
          name: ${{ matrix.jdk }}-test-results
          path: "**/target/*-reports*/**/TEST-*.xml"

      - name: Add coverage to PR
        if: matrix.jdk == 17 && github.event_name == 'pull_request'
        uses: vilmosnagy/jacoco-report@4982e687fa89217b469696f8633358606c4f3172 # 1.8.0
        with:
          paths: jacoco-report/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

  jdk-summary:
    name: JDK Build Summary
    runs-on: ubuntu-latest
    needs: jdk
    if: always()
    steps:
      - name: Check matrix job outcomes
        run: |
          if [[ "${{ needs.jdk.result }}" != "success" ]]; then
            echo "One or more matrix jobs failed."
            exit 1
          else
            echo "All matrix jobs succeeded."
          fi
