name: 'Test Report'
on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed

permissions:
  contents: read

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      actions: read
    strategy:
      matrix:
        jdk: [17, 21, 25]
    steps:
      - name: Download Surefire Report Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ matrix.jdk }}-test-results
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: ${{ matrix.jdk }}

      - uses: rigazilla/action-surefire-report@93b492377a7dde6a3f644cc18d4d74846cac71f3 # summary
        with:
          fail_on_test_failures: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Test Report ${{ matrix.jdk }}
          commit: ${{ github.event.workflow_run.head_sha }}
          ignore_flaky_tests: true
          summary: "Result from workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"
          report_paths: |
            ${{ matrix.jdk }}/**/*-reports*/**/TEST-*.xml
  report-summary:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    needs: report
    if: always()
    steps:
      - name: Check matrix job outcomes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          STATUS="success"
          MESSAGE="All test report jobs succeeded."
          if [[ "${{ needs.report.result }}" != "success" ]]; then
            STATUS="failure"
            MESSAGE="One or more test report jobs failed."
          fi
          curl -s -X POST -H "Authorization: token $GH_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"name\": \"Test Report Summary\", \"head_sha\": \"$SHA\", \"status\": \"completed\",\
               \"conclusion\": \"$STATUS\", \"output\": {\"title\": \"$MESSAGE\", \
               \"summary\":\"\", \"text\":\"\"}}" \
            "https://api.github.com/repos/${{ github.repository }}/check-runs"
